/* eslint-disable @next/next/no-img-element */
/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
// import web1  from '../public/web1.png';
import { useState } from 'react';
import { motion } from "framer-motion";
import Hero from './components/Hero';
import About from './components/About';
import WorkExperience from './components/WorkExperience';
import Skills from './components/Skills';
import Projects from './components/Projects';
import ContactMe from './components/ContactMe';
import Link from 'next/link';
import { SocialIcon } from 'react-social-icons';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const PDF_RESUME = 'https://media.licdn.com/dms/document/C562DAQFUli1JWp3BtA/profile-treasury-document-pdf-analyzed/0/1680094082691?e=1680739200&v=beta&t=9udY5UWSEo7OJwizFZwOf4BLkYcFJXfMMGmMviJJcqQ'

  const downloadResume = (url) => {
    const fileName = url.split('/').pop();
    const aTag = document.createElement('a');
    aTag.href = url;
    aTag.setAttribute('download', fileName);
    aTag.click();
    aTag.remove();
  }

  return (
    <div className={ darkMode ?  "h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-200 scrollbar-thumb-[#F7AB0A]/80" : "dark text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80" }>
      <Head>
        <title>Pablo 💻 Frontend Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-10 dark:bg-[rgb(36,36,36)]'>
          <nav className='sticky top-0 p-5 flex justify-between z-20 max-w-7xl mx-auto xl:items-center'>
            <motion.div
              initial={{
                x: -100,
                opacity: 0,
                scale: 0.5
              }}
              animate={{
                x: 0,
                opacity: 1,
                scale: 1
              }}
              transition={{
                duration: 1.5
              }}>
              <SocialIcon
               url="https://www.linkedin.com/in/pabloescales/"
               fgColor='gray'
               bgColor='transparent'
              />
              <SocialIcon
                url="https://github.com/PabloEscales"
                fgColor='gray'
                bgColor='transparent'
              />
            </motion.div>

            <Link href='#contact'>
              <motion.div
                initial={{
                  x: 100,
                  opacity: 0,
                  scale: 0.5
                }}
                animate={{
                  x: 0,
                  opacity: 1,
                  scale: 1
                }}
                transition={{
                  duration: 1.5
                }}
              >
                <ul className='flex items-center'>
                  <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer dark:text-gray-400'/></li>
                  <li>
                    <a className='bg-yellow-500/80 text-black px-4 flex py-2 rounded-md ml-8 dark:text-gray-800' href='./public/ResumePabloEscalesFrontendWebDeveloper.pdf' download='Resume Pablo Escales Frontend Web Developer' onClick={() => {downloadResume(PDF_RESUME)}}>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-6 h-6 text-white">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M9 13.5l3 3m0 0l3-3m-3 3v-6m1.06-4.19l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
                  </svg>Resume
                    </a>
                  </li>
                  <li>
                    <a className='bg-yellow-500/80 text-black px-4 flex py-2 rounded-md ml-8 dark:text-gray-800' href='#'>
                      ✉️
                    </a>
                  </li>
                </ul>
              </motion.div>
            </Link>
          </nav>

        <section id="hero" className='snap-start dark:text-gray-400'>
          <Hero />
        </section>

        {/* <section id='projects' className='snap-start dark:text-gray-400'>
          <Projects />
        </section> */}

        <section id='experience' className='snap-center dark:text-gray-400'>
          <WorkExperience />
        </section>

        <section id='about' className='snap-center dark:text-gray-400'>
          <About />
        </section>

        <section id='skills' className='snap-start dark:text-gray-400'>
          <Skills />
        </section>

        <section id='contact' className='snap-start dark:text-gray-400'>
          <ContactMe />
        </section>

        <Link href='#hero'>
          <footer className='sticky bottom-5 w-full cursor-pointer'>
            <div className='flex items-center justify-center'>
              <img
                className='h-10 w-16 rounded-full filter grayscale hover:grayscale-0 cursor-pointer'
                src='https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper.png'
                alt=''
              />
            </div>
          </footer>
        </Link>
      </main>
    </div>
  );
}
